name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout Latest
        uses: actions/checkout@master
        with:
          submodules: true
          
      # This GitHub Action handles both the build with Hugo and then deploying
      # the output of the build to our gh-pages branch for deployment
      - name: Hugo Build & Deploy
        uses: mattbailey/actions-hugo@v0.57.2
        if: github.event.deleted == false
#         with:
#           args: --gc --minify
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
